#!/bin/ash
#
# Place this file in /etc/hotplug.d/net/20-counter-reset
#

device="br-lan"
action="add"

if [ "$DEVICENAME" = "$device" -a "$ACTION" = "$action" ]; then
    #Get all the sections that need the run count zero'd                                                                          
    scripts=$(uci show tnscan | grep -i run_count | awk -F. '{ print $2 }' | awk -F'@' '{ print $2 }' | awk -F'[' '{ print $1 }')
                                                     
    for ELEMENT in $scripts; do
	uci set tnscan.@${ELEMENT}[0].run_count='0'
    done

    uci commit tnscan 
fi
