#!/bin/sh /etc/rc.common

START=90
STOP=25
USE_PROCD=1
DAEMON=/usr/sbin/tube
                           
start_service() {
        procd_open_instance tb 
        procd_set_param command $DAEMON
        procd_set_param respawn                                                                                                               
        procd_set_param pidfile /var/run/tube.pid # write a pid file on instance start and remove it on stop
        procd_close_instance                                             
}                                                  
                            
stop_service() {
        service_stop $DAEMON
}                           

reload_service() {
         procd_send_signal tube tb SIGUSR2
} 

