#!/bin/sh
#
# Place this file in /etc/hotplug.d/iface/60-ifup
#set -x
WIFI_INTERFACE="wwan"
ETH_INTERFACE="lan"
MYIPS="192.168.1"
new_file="/tmp/newinit.tmp"
inittab_changed="0"
log_file="/dev/null"  #"/tmp/cblog"

set_inittab()
{
    Echo "Setting inittab for device $DEVICE" >> $log_file
    # If the IP address is not ours then disable the USB tty - security
    IPS=$(ip -o -4 a s $1 | awk '{ print $4 }' | cut -d/ -f1 | awk -F. '{ print $1 "." $2 "." $3}' )
    # Process the /etc/inittab to enable the console if on our network
    # otherwise  disable the console
    echo "$IPS == $MYIPS" >> $log_file

    cat /etc/inittab | grep -v askconsole > $new_file
    console_line=$(cat /etc/inittab | grep -i askconsole)
    no_console_line=$(echo $console_line | grep -i "#")

    if [[ "$IPS" == "$MYIPS" ]]; then
        echo "Enabling console" >> $log_file
        if [ -z "$no_console_line" ]; then
            echo "no_console is empty: $no_console_line" >> $log_file 
            echo "$console_line" >> $new_file
        else
            echo "${no_console_line:1}" >> $new_file
            echo "Changing console to: ${no_console_line:1}"
            inittab_changed="1"
        fi
    fi

    if [[ "$IPS" != "$MYIPS" ]]; then
        echo "Disable console" >> $log_file
        if [ -z "$no_console_line" ]; then
            echo "#$console_line" >> $new_file
            inittab_changed="1"
        else                                        
            echo "${no_console_line}" >> $new_file
        fi                                          
    fi 

    if [ "$inittab_changed" == "1" ]; then
        echo "inittab has changed" >> $log_file
        mv $new_file /etc/inittab
        reboot
    fi 
}


echo  "Starting interface hotplug Device: ${DEVICE} Action: ${ACTION} Interface: ${INTERFACE}" >> $log_file
if [ "$ACTION" = "ifup" -a "$INTERFACE" = "$WIFI_INTERFACE" ]; then
    uci set tnscan.@snoop[0].run_count='0'
    uci set tnscan.@scan[0].run_count='0'
    uci set tnscan.@ports[0].run_count='0'
    uci commit tnscan

    echo "Starting log.." > $log_file
	
	set_inittab $DEVICE
fi


if [ "$ACTION" = "ifup" -a "$INTERFACE" = "$ETH_INTERFACE" ]; then

	set_inittab $DEVICE

fi


if [ "$ACTION" = "ifdown" -a "$INTERFACE" = "$WIFI_INTERFACE" ]; then

fi


